apiVersion: v1
kind: ReplicationController
metadata:
  name: prometheus

spec:
  replicas: 1
  selector:
    app: prometheus
  template:
    metadata:
      name: prometheus
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:v1.4.1
        args:
          - '-storage.local.retention=24h0m0s'
          - '-storage.local.memory-chunks=1000000'
          - '-config.file=/etc/prometheus/prometheus.yml'
          - '-log.level=info'
        resources:
          limits:
            cpu: 1000m
            memory: 1000Mi
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - name: prom-web
          containerPort: 9090
        volumeMounts:
        - name: config-volume
          mountPath: /etc/prometheus
        - name: data
          mountPath: /prometheus/data
      volumes:
      - name: config-volume
        configMap:
          name: prometheus
      - name: data
        hostPath:
          path: /var/lib/docker/prom_data