apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app: prometheus
spec:
  type: LoadBalancer
  externalIPs: [
    "192.168.99.100"
  ]
  ports:
  - name: prom-web
    port: 9090
    targetPort: 9090
  selector:
    app: prometheus