apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-node-1
  namespace: redis-sentinel
  labels:
    app: redis-node-1

spec:
  replicas: 1
  selector:
    app: redis-node-1

  template:
    metadata:
      labels:
        app: redis-node-1
    spec:
      containers:
      - name: redis-node
        image: mpschmidt/elastic-redis:3.2.5-1.1
        imagePullPolicy: IfNotPresent
        env:
        - name: "REDIS_NODE_TYPE"
          value: "SENTINEL_INIT_MASTER"
        - name: "SENTINEL_MASTER_ID"
          value: "mymaster"
        - name: "SENTINEL_SERVICE_HOST"
          value: "${REDIS_SENTINEL_SERVICE_HOST}"
        - name: "SENTINEL_SERVICE_PORT"
          value: "${REDIS_SENTINEL_SERVICE_PORT}"
        - name: "SENTINEL_INIT_MASTER_HOST"
          value: "${REDIS_NODE_1_SERVICE_HOST}"
        - name: "SENTINEL_INIT_MASTER_PORT"
          value: "${REDIS_NODE_1_SERVICE_PORT}"
        - name: "REDIS_CONFIG"
          value: |
            slave-announce-ip ${REDIS_NODE_1_SERVICE_HOST}
            slave-announce-port ${REDIS_NODE_1_SERVICE_PORT}
            appendonly no
        ports:
        - name: redis-port
          containerPort: 6379
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 30
          timeoutSeconds: 5