apiVersion: v1
kind: Service
metadata:
  name: redis-001-node-202
  namespace: redis-cluster
  labels:
    type: cluster
    app: redis
spec:
  ports:
  - name: redis4-db
    port: 6379
    targetPort: 6379
  - name: redis4-cluster
    port: 16379
    targetPort: 16379
  selector:
    app: redis
    node-id: node-202
