apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-node-101
  namespace: redis-cluster
  labels:
    app: redis
    node-id: node-101

spec:
  replicas: 1
  selector:
    app: redis
    node-id: node-101

  template:
    metadata:
      labels:
        app: redis
        node-id: node-101
    spec:
      containers:

      - name: redis-node-101
        image: mpschmidt/elastic-redis:3.2.5-1.0
        imagePullPolicy: IfNotPresent
        command: ["/run.sh"]
        args:
          - "--appendonly no"

        env:
        - name: "REDIS_NODE_TYPE"
          value: "CLUSTER_NODE"
        - name: "CLUSTER_CONFIG"
          value: |
            cluster2-dev--------------redis-node-101 ${REDIS_001_NODE_101_SERVICE_HOST}:${REDIS_001_NODE_101_SERVICE_PORT} myself,master - 0 0 0 connected 0-5460
            cluster2-dev--------------redis-node-102 ${REDIS_001_NODE_102_SERVICE_HOST}:${REDIS_001_NODE_102_SERVICE_PORT} slave - 0 0 0 connected
            cluster2-dev--------------redis-node-201 ${REDIS_001_NODE_201_SERVICE_HOST}:${REDIS_001_NODE_201_SERVICE_PORT} slave - 0 0 0 connected
            cluster2-dev--------------redis-node-202 ${REDIS_001_NODE_202_SERVICE_HOST}:${REDIS_001_NODE_202_SERVICE_PORT} slave - 0 0 0 connected
            cluster2-dev--------------redis-node-301 ${REDIS_001_NODE_301_SERVICE_HOST}:${REDIS_001_NODE_301_SERVICE_PORT} slave - 0 0 0 connected
            cluster2-dev--------------redis-node-302 ${REDIS_001_NODE_302_SERVICE_HOST}:${REDIS_001_NODE_302_SERVICE_PORT} slave - 0 0 0 connected
            vars currentEpoch 0 lastVoteEpoch 0

        - name: "REDIS_CONFIG"
          value: |
            cluster-node-timeout 1000
            cluster-require-full-coverage yes

        ports:
        - name: redis1-port
          containerPort: 6379
          protocol: TCP
        - name: redis1-cluster
          containerPort: 16379
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 30
          timeoutSeconds: 5